### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/site#1117]
I'm getting a error when try to build the website due SSL:

~~~
make[1]: Entering directory '/home/raniere/software-carpentry/site'
python3 ./bin/preprocess.py -c ./config -o /home/raniere/software-carpentry/site/_site -s /home/raniere/software-carpentry/site/_site
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1287, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/preprocess.py", line 248, in <module>
    main()
  File "./bin/preprocess.py", line 72, in main
    config['badges'] = fetch_info(options.amy_url, BADGES_URL)
  File "/home/raniere/software-carpentry/site/bin/util.py", line 76, in fetch_info
    with urllib.request.urlopen(address) as f:
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
Makefile:208: recipe for target '_config.yml' failed
make[1]: *** [_config.yml] Error 1
~~~

**Comment by gvwilson** [comment]
?? Works for me at 14:56 UK time on Thursday Oct 8 2015.

$ hostname
vps1.software-carpentry.org

$ ./remake3.sh
Already on 'master'
Your branch is ahead of 'origin/master' by 3913 commits.
 From https://github.com/swcarpentry/site
  * branch            master     -> FETCH_HEAD
Already up-to-date.
make SITE=http://software-carpentry.org 
OUT=/home/swc/sites/software-carpentry.org build
make[1]: Entering directory `/home/swc/projects/site'
python3 bin/make-dashboard.py ./git-token.txt ./_dashboard_cache.yml
+ swcarpentry/shell-novice
+ swcarpentry/git-novice
+ swcarpentry/hg-novice
+ swcarpentry/sql-novice-survey
+ swcarpentry/python-novice-inflammation
+ swcarpentry/r-novice-inflammation
+ swcarpentry/matlab-novice-inflammation
+ swcarpentry/make-novice
+ swcarpentry/capstone-novice-spreadsheet-biblio
+ DamienIrving/capstone-oceanography
+ swcarpentry/matlab-novice-capstone-biomed
+ swcarpentry/web-data-python
+ swcarpentry/amy
+ swcarpentry/site
python3 ./bin/preprocess.py -c ./config -o 
/home/swc/sites/software-carpentry.org -s http://software-carpentry.org
jekyll build -d /home/swc/sites/software-carpentry.org
Configuration file: /home/swc/projects/site/_config.yml
             Source: /home/swc/projects/site
        Destination: /home/swc/sites/software-carpentry.org
       Generating...
                     done.
  Auto-regeneration: disabled. Use --watch to enable.
python3 ./bin/make-calendar.py -o /home/swc/sites/software-carpentry.org 
-s http://software-carpentry.org
python3 ./bin/make-rss-feed.py -o /home/swc/sites/software-carpentry.org 
-s http://software-carpentry.org
python3 ./bin/make-workshop-rss-feed.py -o 
/home/swc/sites/software-carpentry.org -s http://software-carpentry.org
cp _htaccess /home/swc/sites/software-carpentry.org/.htaccess
make[1]: Leaving directory `/home/swc/projects/site'

**Comment by gvwilson** [comment]
@rgaiacs still occurring?

**Comment by rgaiacs** [comment]
@gvwilson Didn't have time yet. I will check tonight.

**Comment by rgaiacs** [comment]
No problem with `curl`:

~~~
$ curl --verbose https://amy.software-carpentry.org/api/v1/export/instructors.yaml > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.130.229.225...
*   Trying 2001:4802:7805:101:be76:4eff:fe20:c678...
* Immediate connect fail for 2001:4802:7805:101:be76:4eff:fe20:c678: Network is unreachable
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to amy.software-carpentry.org (104.130.229.225) port 443 (#0)
* found 181 certificates in /etc/ssl/certs/ca-certificates.crt
* found 728 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.software-carpentry.org (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: OU=Domain Control Validated,OU=Hosted by A Small Orange LLC,OU=PositiveSSL Wildcard,CN=*.software-carpentry.org
*        start date: Sat, 31 Jan 2015 00:00:00 GMT
*        expire date: Sun, 31 Jan 2016 23:59:59 GMT
*        issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
*        compression: NULL
* ALPN, server did not agree to a protocol
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0> GET /api/v1/export/instructors.yaml HTTP/1.1
> Host: amy.software-carpentry.org
> User-Agent: curl/7.44.0
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< HTTP/1.1 200 OK
< Server: nginx/1.4.6 (Ubuntu)
< Date: Sat, 10 Oct 2015 02:13:36 GMT
< Content-Type: application/yaml; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Allow: GET, HEAD, OPTIONS
< Vary: Accept, Cookie
< X-Frame-Options: SAMEORIGIN
< 
{ [16121 bytes data]
100 35435    0 35435    0     0  14497      0 --:--:--  0:00:02 --:--:-- 14492
* Connection #0 to host amy.software-carpentry.org left intact
~~~

But with Python:

~~~
$ python3
Python 3.4.3+ (default, Sep 23 2015, 17:53:22) 
[GCC 5.2.1 20150911] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> f = urllib.request.urlopen("http://amy.software-carpentry.org/api/v1/export/instructors.yaml")
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 871, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1211, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
~~~

I'm closing this because probably is something related with my connection. =(

**Comment by rgaiacs** [comment]
> I'm closing this because probably is something related with my connection. =(

Re-open this since this isn't related with my connection. Maybe **Python 3.5.0** related.

**Comment by jduckles** [comment]
Is AMY using a self-signed certificate? I think the problem is with the `urllib` fetches to AMY.

**Comment by jduckles** [comment]
Per PEP 476

Just tried this and it fixes things....@gvwilson, can you check if it breaks things on older than 3.5.0:
```
diff --git a/bin/util.py b/bin/util.py
index 88609a2..54f1f4c 100644
--- a/bin/util.py
+++ b/bin/util.py
@@ -73,7 +73,9 @@ def load_info(folder, filename=CONFIG_YML):
 def fetch_info(base_url, url):
     """Download a file and save it."""
     address = base_url + url
-    with urllib.request.urlopen(address) as f:
+    import ssl
+    context = ssl._create_unverified_context()
+    with urllib.request.urlopen(address, context=context) as f:
         content = f.read()
     return yaml.load(content.decode('utf-8'))
```

If all is good I'll do a clean PR

**Comment by rgaiacs** [comment]
@jduckles I don't think that we want to disable SSL.

**Comment by jduckles** [comment]
We're not disabling SSL, just strict certificate checking.  Yes, this is a problem, the right way to fix is to not use a self-signed certificate.  We need to pay for an SSL certificate, or wait for http://letsencrypt.org to come online here in a month or so.

**Comment by pbanaszkiewicz** [comment]
@jduckles AMY's not using a self-signed certificate. It's using a wildcard `*.software-carpentry.org` certificate signed by COMODO.

Folks, on my disk the bin/util.py function fetch_info looks completely different and I think safer:

```python
def fetch_info(base_url, url):
    """Download a file and save it."""
    address = base_url + url

    # loads operating system's trusted CA certificates
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)

    with urllib.request.urlopen(address, context=ssl_context) as f:
        content = f.read()
    return yaml.load(content.decode('utf-8'))
```

Not sure if this never landed in `site`, or was overwritten…

**Comment by gvwilson** [comment]
Does not appear to work with Python 3.3.5 / Anaconda 2.1.0 - 
urllib.request.urlopen does not have a keyword argument 'context'. Is 
there some other library I should install on top of Py3 to make this work?

**Comment by pbanaszkiewicz** [comment]
‎As per https://www.python.org/dev/peps/pep-0476/ you have to be on Python 3.4.3 or higher to have that argument.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Greg WilsonSent: Monday, 19 October 2015 10:17To: swcarpentry/siteReply To: swcarpentry/siteCc: Piotr BanaszkiewiczSubject: Re: [site] SSL: CERTIFICATE_VERIFY_FAILED (#1117)Does not appear to work with Python 3.3.5 / Anaconda 2.1.0 - 
urllib.request.urlopen does not have a keyword argument 'context'. Is 
there some other library I should install on top of Py3 to make this work?


—Reply to this email directly or view it on GitHub.

**Comment by gvwilson** [comment]
So, time to upgrade my Python? :-(

**Comment by rgaiacs** [comment]
@pbanaszkiewicz Your patch does not work on my machine.

~~~
$ uname -a
Linux pupunha 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 GNU/Linux
$ make --version
GNU Make 4.0
$ python3 --version
Python 3.4.3+
$ git --version
git version 2.6.1
$ git rev-parse HEAD
a33ae48c11dfcc514d39237a53ef26d429ec0c46
$ git diff
diff --git a/bin/util.py b/bin/util.py
index 88609a2..3019253 100644
--- a/bin/util.py
+++ b/bin/util.py
@@ -6,6 +6,7 @@ Utilities for site regeneration.
 import os
 import re
 import urllib.request
+import ssl
 import yaml
 import sys
 from PyRSS2Gen import RSS2, RSSItem
@@ -73,6 +74,10 @@ def load_info(folder, filename=CONFIG_YML):
 def fetch_info(base_url, url):
     """Download a file and save it."""
     address = base_url + url
+
+    # loads operating system's trusted CA certificates
+    ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
+
     with urllib.request.urlopen(address) as f:
         content = f.read()
     return yaml.load(content.decode('utf-8'))
$ make -B site
make SITE=/home/raniere/software-carpentry/site/_site OUT=/home/raniere/software-carpentry/site/_site build
make[1]: Entering directory '/home/raniere/software-carpentry/site'
python3 bin/make-dashboard.py ./git-token.txt ./_dashboard_cache.yml
python3 ./bin/preprocess.py -c ./config -o /home/raniere/software-carpentry/site/_site -s /home/raniere/software-carpentry/site/_site
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1287, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/preprocess.py", line 248, in <module>
    main()
  File "./bin/preprocess.py", line 72, in main
    config['badges'] = fetch_info(options.amy_url, BADGES_URL)
  File "/home/raniere/software-carpentry/site/bin/util.py", line 81, in fetch_info
    with urllib.request.urlopen(address) as f:
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
Makefile:208: recipe for target '_config.yml' failed
make[1]: *** [_config.yml] Error 1
make[1]: Leaving directory '/home/raniere/software-carpentry/site'
Makefile:84: recipe for target 'site' failed
make: *** [site] Error 2
~~~

**Comment by gvwilson** [comment]
@raniere @pbanaszkiewicz status of this one?

**Comment by rgaiacs** [comment]
@gvwilson I think that you or @jduckles solve this.
